#!/usr/bin/env bash

# Set up autograder files

cp -rn /autograder/submission/* /autograder/source/

cd /autograder/source

npx prisma migrate reset --force && npx prisma migrate dev --name init  && npm run seed
npx jest --detectOpenHandles --testResultsProcessor jest-autograding-reporter
cp /autograder/source/results.json /autograder/results/results.json